name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: cvtool-ui
  AZURE_RESOURCE_GROUP: az-rg-rmdy-cv-agent
  CONTAINER_REGISTRY: crRmdyCvAgent
  CONTAINER_APP_ENVIRONMENT: cvtool-env
  CONTAINER_APP_NAME: cvtool-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }} .
        docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Register Container Apps provider
      run: |
        az provider register --namespace Microsoft.App --wait
        az provider show --namespace Microsoft.App --query "registrationState"

    - name: Create Container Apps Environment (if not exists)
      if: github.ref == 'refs/heads/main'
      run: |
        az containerapp env create \
          --name ${{ env.CONTAINER_APP_ENVIRONMENT }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --location 'France Central' \
          --only-show-errors || echo "Environment already exists"

    - name: Deploy to Azure Container Apps
  if: github.ref == 'refs/heads/main'
  run: |
    az containerapp create \
      --name ${{ env.CONTAINER_APP_NAME }} \
      --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
      --environment ${{ env.CONTAINER_APP_ENVIRONMENT }} \
      --image crrmdycvagent.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }} \
      --target-port 3000 \
      --ingress external \
      --env-vars \
        AZURE_SQL_SERVER=${{ secrets.AZURE_SQL_SERVER }} \
        AZURE_SQL_DATABASE=${{ secrets.AZURE_SQL_DATABASE }} \
        AZURE_SQL_USER=${{ secrets.AZURE_SQL_USER }} \
        AZURE_SQL_PASSWORD=${{ secrets.AZURE_SQL_PASSWORD }} \
        AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
      --cpu 0.25 \
      --memory 0.5Gi \
      --min-replicas 0 \
      --max-replicas 1 \
      --only-show-errors || \
    # Update existing container app
    az containerapp update \
      --name ${{ env.CONTAINER_APP_NAME }} \
      --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
      --image crrmdycvagent.azurecr.io/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }} \
      --set-env-vars \
        AZURE_SQL_SERVER=${{ secrets.AZURE_SQL_SERVER }} \
        AZURE_SQL_DATABASE=${{ secrets.AZURE_SQL_DATABASE }} \
        AZURE_SQL_USER=${{ secrets.AZURE_SQL_USER }} \
        AZURE_SQL_PASSWORD=${{ secrets.AZURE_SQL_PASSWORD }} \
        AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
      --cpu 0.25 \
      --memory 0.5Gi \
      --min-replicas 0 \
      --max-replicas 1 \
      --only-show-errors

          